[build]
  command = "npm run build"
  publish = "frontend"

# https://docs.netlify.com/build/configure-builds/file-based-configuration/#functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# reCAPTCHA site key is exposed at build time
[[headers]]
  for = "/api/recaptcha"
  [headers.values]
    Content-Type = "application/json" # @todo somehow does not work
    Access-Control-Allow-Origin = "*"

# rewrite other API requests to netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404